# Generated by Django 5.2 on 2025-04-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("youtube_link", models.URLField()),
                ("thumbnail", models.URLField()),
                ("uploaded_date", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.IntegerField(default=0)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
